// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {base} from '../models';

export function Clear(arg1:string):Promise<void>;

export function CounterKey(arg1:base.Address,arg2:base.Address):Promise<string>;

export function Export(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function OpenUrl(arg1:string):Promise<void>;

export function Reload(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetChain(arg1:string,arg2:string):Promise<void>;

export function Summarize(arg1:base.Address,arg2:string):Promise<void>;
