// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1, arg2, arg3) {
  return window['go']['main']['App']['Export'](arg1, arg2, arg3);
}

export function Reload(arg1, arg2, arg3) {
  return window['go']['main']['App']['Reload'](arg1, arg2, arg3);
}
