// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Reload(arg1:string,arg2:string,arg3:boolean):Promise<string>;
