// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear(arg1, arg2) {
  return window['go']['main']['App']['Clear'](arg1, arg2);
}

export function CounterKey(arg1, arg2) {
  return window['go']['main']['App']['CounterKey'](arg1, arg2);
}

export function Export(arg1, arg2) {
  return window['go']['main']['App']['Export'](arg1, arg2);
}

export function Freshen(arg1, arg2) {
  return window['go']['main']['App']['Freshen'](arg1, arg2);
}

export function OpenUrl(arg1) {
  return window['go']['main']['App']['OpenUrl'](arg1);
}

export function SetAddress(arg1) {
  return window['go']['main']['App']['SetAddress'](arg1);
}

export function SetChain(arg1, arg2) {
  return window['go']['main']['App']['SetChain'](arg1, arg2);
}

export function SetChartType(arg1) {
  return window['go']['main']['App']['SetChartType'](arg1);
}

export function SetExportExcel(arg1) {
  return window['go']['main']['App']['SetExportExcel'](arg1);
}

export function Summarize(arg1) {
  return window['go']['main']['App']['Summarize'](arg1);
}
